
version: '3.1'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blancdb
      MYSQL_USER: blancdb
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080


      ## QUAY IMAGE

  # keycloak:
  #   image: quay.io/keycloak/keycloak:22.0.5     
  #   command: start-dev
  #   environment:
  #     KC_DB: mysql
  #     KC_DB_URL_HOST: db
  #     KC_DB_URL_DATABASE: blancdb
  #     KC_DB_URL_PASSWORD: password
  #     # KC_DB_SCHEMA
  #     KEY

      ## JBOSS IMAGE

    # kc-db:
    #   image: mysql:latest
    #     ports:
    #       - 3366:3306
    #     restart: unless-stopped
    #     environment:
    #       # The user, password and database that Keycloak
    #       # is going to create and use
    #       MYSQL_USER: blancdb
    #       MYSQL_PASSWORD: password
    #       MYSQL_DATABASE: blanckc
    #       MYSQL_ROOT_PASSWORD: password
    #   volumes:
    #     -keycloak-and-mysg1-volume:/var/lib/mysal
    #   networks:
    #     - keycloak-and-mysql-network

    #   keycloak-w:
    #     image: jboss/keycloak:16.1.0
    #     ports:
    #       - 9081:8089
    #     restart: unless-stopped
    #     environment:
    #       # User and password for the Administration Console
    #       KEYCLOAK_USER=admin
    #       KEYCLOAK_PASSWORD=password
    #       DB_VENDOR-mysql


      ## QUAY IMAGE with mysql
  # keycloak_mysql:
  #     image: mysql:latest
  #     environment:
  #       MYSQL_ROOT_PASSWORD: root
  #       MYSQL_DATABASE: keycloak
  #       MYSQL_USER: blancdb
  #       MYSQL_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      command: start-dev
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: db
        DB_DATABASE: keycloak
        DB_USER: blancdb
        DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: password  
        KEYCLOAK_USER: user
        KEYCLOAK_PASSWORD: password
      ports:
        - 8088:8080
      depends_on:
        - db

# volumes:
#   mysql-data:
#   # keycloak-and-mysg1-volume:




volumes:
  mysql-data:


