# name: blancspace
# version: '3.1'
# services:
#   db:
#     image: mysql:latest
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: blancdb
#       MYSQL_USER: 
#       MYSQL_PASSWORD: 
#     ports:
#         - 3306:3306
#     volumes: 
#       #named volume
#       - mysql-data:/var/lib/mysql
#       
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8089:8080
#       
# volumes:
#   mysql-data:

######

version: '3.1'
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: blancdb
      MYSQL_USER: blancdb
      MYSQL_PASSWORD: Blancdb123!
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080

volumes:
  mysql-data:


# docker run --name mysqltest -e MYSQL_ROOT_PASSWORD=password -d mysql:tag


# version: '3.8'
# services:
#   mysql:
#     image: mysql:8.0
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: blancdb
#     volumes:
#       - mysql-data:/var/lib/mysql
#       
#       
#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080
# volumes:
#   mysql-data:
